### ISSUE TITLE
[SUGGESTION]Hide Tab Completely, But Conten Can still be Search

### ISSUE THREAD

**Issue by ardissaps** [hypherionmc/MoreCreativeTabs#1]
Also feature to move certain item to another tab. Well the purpose is actually to clean tab right?

**Comment by hypherionmc** [comment]
Hi there. How do you mean searched for?

Also items can be removed from their original tabs and placed in a custom one, but not other already present tabs

**Comment by ardissaps** [comment]
> Hi there. How do you mean searched for?
> 
> Also items can be removed from their original tabs and placed in a custom one, but not other already present tabs

I was hoping I can use it with https://modrinth.com/mod/reasonable-sorting, that mod move item to spesific tab (any). Then use your mod to hide the empty tab. If can

**Comment by hypherionmc** [comment]
The anytab moving can probably be added. Shouldn't be too hard. Also I've been trying to find a way to completely remove the disabled tabs, so they don't show up in the game at all, but everything I've tried so far just completely broke the inventory

**Comment by hypherionmc** [comment]
Should be do-able with any of the latest releases
