### ISSUE TITLE
crash with many items in tab?

### ISSUE THREAD

**Issue by ghost** [hypherionmc/MoreCreativeTabs#2]
**Describe the bug**

**To Reproduce**
  1. Go to 'Try to create a custom tab with a ton of items. in my case 486'
  2. Click on 'reload and open creative'
  3. Crash
  4. reload the game and see that the custom tab didn't load
  5. wonder why nothing works

**Expected behavior**
I expected the custom tab to appear like the example pack but instead it crashed

**Screenshots**
It just says saving world at time of crash

**Version**
- Minecraft Version: 1.19.2
- Mod loader
  -Fabric
- Mod Loader Version:
- Mod Version: 1.1.0

**Additional context**
I have a few other mods enabled like REI for instance They can be seen in the crash report. The example pack work with it so it should be fine. The pack that I was using will be attached. I tried remaking the 1.19.3 creative building tab and was going to back port the other tabs but it kept crashing before i could finish this one

**Crash Report**
https://mclo.gs/SSPj5i9
[1.19.3 Building tab.zip](https://github.com/hypherionmc/MoreCreativeTabs/files/9860191/1.19.3.Building.tab.zip)

**Comment by hypherionmc** [comment]
Hi.

You have a bunch of JSON errors in your file, which is why the game crashes when you reload/load it

You can test it with https://jsonlint.com/

**Comment by hypherionmc** [comment]
This is the file without errors, so it should load fine: https://paste.firstdarkdev.xyz/inupisidak.json

**Comment by hypherionmc** [comment]
**Note to self: Add error handling for files with invalid syntax and display an ingame error instead of having the game crash**
