### ISSUE TITLE
[BUG] Crashing when unloading resourcepack and /mct reload

### ISSUE THREAD

**Issue by Boy0000** [hypherionmc/MoreCreativeTabs#3]
**Describe the bug**
When using a resourcepack with the JSON files in it, then removing said resourcepack and reloading, the map becomes empty and opening the inv crashes you

**To Reproduce**
  1. Enable any resourcepack with MoreCreativeTabs files in it
  2. /mct reloadTabs
  3. Remove said pack
  4. /mct reloadTabs
  5. Open inventory
  6. See error

**Expected behavior**
Opening the pure vanilla inventory

**Screenshots**

https://user-images.githubusercontent.com/62521371/204922697-8de97ea0-703e-4a22-b36d-3a48ed6de59d.mp4

**Versions (DO NOT USE "LATEST"! I STEAL YOUR KNEE CAPS!):**
- Minecraft Version: 1.19.2
- Modloader
  - [ ] Forge
  - [X] Fabric
- Mod Loader Version: 0.14.9
- Mod Version: 1.2.0

**Additional context**
Simply re-loading the original ResourcePack and /mct reloadTabs does not fix the issue either. It seems a full on restart is needed

**Crash Report**
If the game crashed, please include your latest crash report here
https://hastebin.com/ezeqejufot.yaml

**Comment by hypherionmc** [comment]
Hmmmm. Looks like something went wrong when it's supposed to restore the old, unmodified tabs

**Comment by hypherionmc** [comment]
Issue doesn't appear to be present in latest releases anymore
