### ISSUE TITLE
[BUG] Items don't display correct tab while searching

### ISSUE THREAD

**Issue by Pipsqueak737** [hypherionmc/MoreCreativeTabs#5]
In the search tab, items show up as being in different tabs than what they're meant to be. For example, searching "sword" and hovering over the swords shows them as being in the "Food & Drinks" tab.

I'm using the Amended resource pack as well.

- Minecraft Version: 1.19.2
- Modloader: Forge
- Mod Loader Version: 43.2.8
- Mod Version: 1.2.0

**Comment by hypherionmc** [comment]
This is a known issue with the mod. The idea was to address this along with any bugs that popped up in the 1.19.3/4 version, of which there are a couple now.

**Comment by hypherionmc** [comment]
Fixed with 1.2.1
