### ISSUE TITLE
[BUG] Game fails to launch with most recent update

### ISSUE THREAD

**Issue by DaRealSparky** [hypherionmc/MoreCreativeTabs#6]
**Describe the bug**
Upon clicking play, the game crashes with Exit Code 1.

**To Reproduce**
  1. Install Forge version 40.2.2
  2. Install mod version 1.2.1 (latest version at time of writing)
  3. Launch game

**Expected behavior**
Game should load normally.

**Screenshots**
N/A

**Versions (DO NOT USE "LATEST"! I STEAL YOUR KNEE CAPS!):**
- Minecraft Version: 1.18.2
- Modloader
  - [X] Forge
  - [ ] Fabric
  - [ ] Quilt
- Mod Loader Version: 40.2.2
- Mod Version: 1.2.1

**Additional context**
Issue is not mod incompatibility as the problem persists with only this mod installed.

**Crash Report**
Exit Code 1 does not appear to generate a crash log. I have instead provided the [debug.log](https://github.com/hypherionmc/MoreCreativeTabs/files/11378793/debug.log) and [latest.log](https://github.com/hypherionmc/MoreCreativeTabs/files/11378797/latest.log) files from my last test with only this mod installed.

**Comment by Pipsqueak737** [comment]
I can confirm this happens with me as well.

**Comment by hypherionmc** [comment]
For now just downgrade to the older version again. My stupid country doesn't have power when I'm at home, so it might be a while before I can check this out myself. Hopefully over the weekend I'll get some time

**Comment by DaRealSparky** [comment]
Any update on this? Not having to relaunch the game while editing is an incredible feature that speeds up work and I can't wait to use it.

**Comment by hypherionmc** [comment]
Issue fixed in 1.2.2
