### ISSUE TITLE
[BUG] Disabling any vanilla tab breaks all tab positioning

### ISSUE THREAD

**Issue by ghost** [hypherionmc/MoreCreativeTabs#7]
**Describe the bug**
I tried disabling the following tabs in `assets/minecraft/morecreativetabs/disabled_tabs.json`:

- building_blocks
- decorations
- redstone
- transportation
- misc
- food
- tools
- combat
- brewing

Doing so hides the tabs from the creative menu, but it also breaks the positioning of all other custom tabs, placing them in unintended spots. There are normally 6 tabs on the top of the menu (4 on the top left, a gap in the middle, and 2 on the right) but with this bug there are 5 on the left before the gap appears. The Fabric left and right arrow buttons are also clipping into the tabs and are unclickable.

**To Reproduce**
  1. Install the specified MC/Fabric/mod version specified below
  2. Enable the provided resource pack for my MoreCreativeTabs setup
  3. Join a singleplayer world and open the creative menu

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/108554062/236367847-534c7089-0056-4e8c-a3f9-cbe2acdc2975.png)

**Versions:**
- Minecraft Version: 1.19.2
- Modloader
  - [✓] Fabric
- Mod Loader Version: 0.14.19
- Mod Version: MoreCreativeTabs-combo-1.19-1.2.1

**Additional context**
Curious for more information, I installed the FancyMenu mod and used it to manually move Fabric's buttons to make them clickable again. Here's a video with my findings:

https://user-images.githubusercontent.com/108554062/236368495-7e70edf1-4397-49b3-afd8-005c3d6894fa.mp4

It looks like the search, saved hotbars, and survival inventory tabs are forcing themselves to be the first 3 tabs in every page (those are the only 3 vanilla tabs I left enabled.) They're even overlapping with other tabs. I tried clicking the other tabs underneath them, but those 3 were prioritized every time.

**Relevant Files**
[Latest Log](https://gist.github.com/Puffadillo/4ee9cc6705bf09b7539b7f365bacf7d9)
[Tabs.Resource.Pack.zip](https://github.com/hypherionmc/MoreCreativeTabs/files/11403001/Tabs.Resource.Pack.zip)
(Tested on a fresh instance with only Fabric API and MoreCreativeTabs)

**Comment by hypherionmc** [comment]
Urgh why are those fucking buttons not moved... Why does this damn mod keep on breaking.

I'm gonna push to replace the entire inventory screen with a custom one, cause I'm getting tired of this. But thanks for providing clarity on it

**Comment by hypherionmc** [comment]
Issue fixed in 1.2.2
