### ISSUE TITLE
[BUG] Why is the tab order like this?

### ISSUE THREAD

**Issue by DTech10** [hypherionmc/MoreCreativeTabs#8]
**Describe the bug**
I removed the Saved Hotbars tab and the tab order turned into this, is there a way to change the order?
The Inventory and Search tab goes back to normal order when go to other pages

Also when I install the [Skeleton Pack](https://morecreative.fdd-docs.com/create-tab/) to remove some tabs, the Extended tab from the mod [Extended Creative Inventory](https://www.curseforge.com/minecraft/mc-mods/extended-creative-inventory) gets removed even though I didnt list it in the "disabled_tabs"

**To Reproduce**
  1. Remove 'Saved Hotbars(hotbar) tab

**Screenshots**
![2023-07-16_15 17 21](https://github.com/hypherionmc/MoreCreativeTabs/assets/136813833/0856115d-a575-4561-ac39-004448a02012)
![2023-07-16_15 17 24](https://github.com/hypherionmc/MoreCreativeTabs/assets/136813833/6b4e6144-11a0-4541-9bf4-8c8584b338b1)
![2023-07-16_15 17 29](https://github.com/hypherionmc/MoreCreativeTabs/assets/136813833/f3980ef5-30c5-4a71-8efb-d955e1e9701d)

**Versions (DO NOT USE "LATEST"! I STEAL YOUR KNEE CAPS!):**
- Minecraft Version: 1.19.2
- Modloader
  - [dis] Forge
- Mod Loader Version: 43.2.19
- Mod Version: 1.2.2

I typed "tab(s)" 8 times

**Comment by hypherionmc** [comment]
That's intended behavior. When a tab is disabled, all other tabs move over to fill the slot. You can re-order tabs yourself using the orderedtabs file. There is some info on the wiki about how to use that feature

**Comment by DTech10** [comment]
Okay thx!
